a=int(input("enter the number "))

try:
    print(a)
except Exception as e:
    print(e)


    # finally is used in function to show smth. it will run eventhough it return something previously...